spring:
  application:
    name: investment-manager-api
  datasource:
    url: jdbc:mysql://localhost:3306/investment-db
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:  
    show-sql: true
    hibernate:
      ddl-auto: update
